# Use global profile when available
if [ -f /usr/share/defaults/etc/profile ]; then
    . /usr/share/defaults/etc/profile
fi

# allow admin overrides
if [ -f /etc/profile ]; then
    . /etc/profile
fi

if [[ ":$PATH:" != *":$HOME/Bin:"* ]]; then
    export PATH="${PATH}:${HOME}/Bin"
fi

if [[ "$GOPATH" != "$HOME/Projects/go" ]]; then
    export GOPATH="${HOME}/Projects/go"
fi

if [[ ":$PATH:" != *":$GOPATH/bin:"* ]]; then
    export PATH="${PATH}:${GOPATH}/bin"
fi

if [[ "$BASH_COMPLETION_USER_DIR" != "${HOME}/.local/share/bash-completion" ]]; then
    export BASH_COMPLETION_USER_DIR="${HOME}/.local/share/bash-completion"
fi

# include files in .bash_exports
if [ -d .bash_exports ]; then
    pushd .bash_exports > /dev/null
    for file in * ; do
        if [ -f "${file}" ]; then
            . "$file"
        fi
    done
    popd > /dev/null
fi

