#!/bin/bash

_GOBASE="${HOME}/Projects/go"

if [[ -d "${_GOBASE}" ]]; then
    if [[ "$GOPATH" != "${_GOBASE}" ]]; then
        export GOPATH="${_GOBASE}"
    fi

    if [[ ":$PATH:" != *":${GOPATH}/bin:"* ]]; then
        export PATH="${PATH}:${GOPATH}/bin"
    fi
fi
