#!/bin/bash
# Copyright (C) 2020 Jef Oliver.
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
# IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# Authors:
# Jef Oliver <jef@eljef.me>

# shellcheck source=/home/dev/Bin/include/eljef-bash-common
. "${HOME}/Bin/include/eljef-bash-common"

HELPSTATEMENT=$(cat <<- EOF

    convert-to-mp3

    Converts m4a, mp4, and flac files to 320k mp3 files.
EOF
)

check_help "${1}"

if [ -n "$(ls -1 ./*.m4a 2>/dev/null)" ]; then
    for i in *.m4a
    do
        print_leader_full "ffmpeg -i \"${i}\" -ab 320k \"${i%.m4a}.mp3\""
        ffmpeg -i "${i}" -ab 320k "${i%.m4a}.mp3" > /dev/null 2>&1
    done
elif [ -n "$(ls -1 ./*.mp4 2>/dev/null)" ]; then
    for i in *.mp4
    do
        print_leader_full "ffmpeg -i \"${i}\" -ab 320k \"${i%.mp4}.mp3\""
        ffmpeg -i "${i}" -ab 320k "${i%.mp4}.mp3" > /dev/null 2>&1
    done
elif [ -n "$(ls -1 ./*.flac 2>/dev/null)" ]; then
    for i in *.flac
    do
        print_leader_full "ffmpeg -i \"${i}\" -ab 320k \"${i%.flac}.mp3\""
        ffmpeg -i "${i}" -ab 320k "${i%.flac}.mp3" > /dev/null 2>&1
    done
fi

