#!/bin/bash
# Copyright (C) 2020 Jef Oliver.
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
# IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# Authors:
# Jef Oliver <jef@eljef.me>
#
# Assumes this directory contains artist folders with ablum folders, as such:
# Artist/
#    Album1/
#    Album2/
#
# Album folders need to have a cover.jpg or cover.png file in them.
#
# Albums must be in mp3 format.

# shellcheck source=/home/dev/Bin/include/eljef-bash-common
. "${HOME}/Bin/include/eljef-bash-common"

function prep_mp3s() {
    for MP3FILE in *.mp3
    do
        print_leader "${MP3FILE}"
        artist=$(ffprobe "${MP3FILE}" 2>&1 | sed -E -n 's/^ *album_artist *: (.*)/\1/p';)
        eyeD3 -Q -l error --remove-all-images "${MP3FILE}" > /dev/null
        if [ -n "${artist}" ]; then
            eyeD3 -Q -l error --add-image cover.jpg:FRONT_COVER --user-text-frame "ALBUMARTISTSORT:${artist}" --text-frame "TSOP:${artist}" "${MP3FILE}" > /dev/null
        else
            eyeD3 -Q -l error --add-image cover.jpg:FRONT_COVER "${MP3FILE}" > /dev/null
        fi
    done
}

function start_prep() {
    print_leader "cover.jpg"
    convert "${1}" -resize 600x600\> cover.new.jpg
    rm "${1}"
    mv cover.new.jpg cover.jpg
    print_copy_move_with_seg "cover.jpg" "folder.jpg"
    cp cover.jpg folder.jpg
}

CWD="$(pwd)"
IFS=$'\n'
for MP3DIR in $(find . -type f -name '*.mp3' | sed -r 's|/[^/]+$||' | sort -u)
do
    print_leader "${MP3DIR}"
    cd_or_error "${MP3DIR}"
    if [ -f "folder.jpg" ]; then
        print_leader " ${WARN_START}EXISTS${RESET} ${SYM_SEG}"
        print_leader " ${WARN_START}EXISTS${RESET} ${SYM_SEG} ${SYM_END} ${WARN_START}FOLDER.JPG EXISTS${RESET} ${SYM_DLM} ${WARN_START}SKIPPING${RESET}"
        print_leader " ${WARN_START}EXISTS${RESET} ${SYM_SEG}"
    elif [ -f "cover.jpg" ]; then
        start_prep cover.jpg
        prep_mp3s
    elif [ -f "cover.png" ]; then
        start_prep cover.png
        prep_mp3s
    else
        print_leader " ${ERROR_START}ERROR${RESET} ${SYM_SEG}"
        print_leader " ${ERROR_START}ERROR${RESET} ${SYM_SEG} ${SYM_END} ${ERROR_START}NO COVER FOUND${RESET} ${SYM_DLM} ${ERROR_START}SKIPPING${RESET}"
        print_leader " ${ERROR_START}ERROR${RESET} ${SYM_SEG}"
    fi
    cd_or_error "${CWD}"
done
