#!/bin/bash
# Copyright (C) 2020 Jef Oliver.
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
# IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# Authors:
# Jef Oliver <jef@eljef.me>

function check_location() {
    SCRIPT=$(dirname "$0")
    SDIR=$(realpath "${SCRIPT}${1}")
    BASE=$(basename "${SDIR}")

    if [ "${BASE}" != "dotfiles" ]; then
        echo_error "Could not determine base dotfiles directory."
    fi

    cd "${SDIR}" || echo_error "Could not change directories to base dotfiles directory."

    if [ "$(ls -1d dotfiles)" != "dotfiles" ]; then
        echo_error "Could not determine base dotfiles directory."
    fi

    echo "${SDIR}"
}

function check_root() {
    if [ "${EUID}" -ne 0 ]; then
        echo_error "This script must be run with root privileges."
    fi
}

function copy_dir() {
    if [ "${1}" != "" ] && [ "${2}" != "" ]; then
        echo " --==-- ${1} -> ${2}"
        cp -R "${1}" "${2}" || echo_error "Could Not Copy: ${1} -> ${2}"
    fi
}

function delete_file() {
    if [ "${1}" != "" ]; then
        if [ "${2}" != "quiet" ]; then
            echo " --==-- Deleting ${1}"
            rm "${1}" || echo_error "Could not delete ${1}"
        fi
    fi
}

function echo_error() {
      if [ "${1}" != "" ]; then
          echo "${1}"
      fi
      exit 1
}

function install_file() {
    if [ "${1}" != "" ] && [ "${2}" != "" ]; then
        echo " --==-- ${1} -> ${2}"
        cp -f "${1}" "${2}" || echo_error "Could not copy file: ${1} -> ${2}"
        if [ "${3}" != "" ]; then
            chmod "${3}" "${2}" || echo_error "Could not change mode: ${2} == ${3}"
        fi
    fi
}

function make_directory() {
    if [ "${1}" != "" ]; then
        echo " --==-- mkdir -p ${1}"
        mkdir -p "${1}" || echo_error "Could not create directory: ${1}"
    fi
}

